language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t owenyi3207/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true owenyi3207/react-test-app yarn run test

after_success:
  - docker build -t owenyi3207/docker-frontend ./frontend
  - docker build -t owenyi3207/docker-backend ./backend
  - docker build -t owenyi3207/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push owenyi3207/docker-frontend
  - docker push owenyi3207/docker-backend
  - docker push owenyi3207/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-fullstack-app"
  env: "DockerFullStackApp-env"
  bucket_name: elasticbeanstalk-us-east-2-310881911728
  bucket_path: "docker-fullstack-app"
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY